### ISSUE TITLE
dockerd.exe missing after choco upgrade

### ISSUE THREAD

**Issue by Hvid** [slonopotamus/stevedore#34] opened 2022-03-14 12:47 UTC
### Stevedore Version

0.3.2

### Windows Version

Microsoft Windows [Version 10.0.20348.524]

### Log output

[stevedore.log](https://github.com/slonopotamus/stevedore/files/8244871/stevedore.log)

### Additional context

Previously running 0.0.6.
Did a choco upgrade stevedore -y via puppet and rebooted afterwards. dockerd.exe is missing after the upgrade and service cannot start.

If i force another upgrade to the same version, it works. Maybe the service isn't stopped correct and then the file cannot be overwritten? It is deleted though.

Note: the service name is 'docker' for this install.

**Comment by Hvid** [comment] 2022-03-14 12:57
Yes., exactly. I was thinking that maybe the stop fails due to the service being renamed in the first place.

**Comment by Hvid** [comment] 2022-03-14 12:57
Also, this was with puppet, so executed by localsystem user.

**Comment by slonopotamus** [comment] 2022-03-14 12:59
This might be caused by the fact that `dockerd` MSI component [doesn't have a fixed GUID](https://github.com/slonopotamus/stevedore/blob/0.3.2/wix/main.wxs#L74)... Will try using some fixed value. Note that the same thing can happen *once more* when you will be upgrading from non-fixed GUID to fixed one, but should not occur after that (if it will still happen, this issue will need to be reopened).

**Closed** 2022-03-14 15:36 UTC
Labels: bug

**Comment by slonopotamus** [comment] 2022-03-14 15:38
Fix released as stevedore-0.3.3. Might take some time to be published on GH releases / Chocolatey. As I said, you might notice *one more* dissapearing of `dockerd.exe` when updating from <0.3.3 to >=0.3.3, but this should never happen again after that 0.3.3.

**Comment by Hvid** [comment] 2022-03-15 06:38
Hey, just wanted to let you know that dockerd.exe did not get removed during the upgrade from 0.3.2 to 0.3.3.
